// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxizziemihdlcprrfhjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aXp6aWVtaWhkbGNwcnJmaGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzM1NTcsImV4cCI6MjA2ODQwOTU1N30.ImQp7J6fpFcxgYzzAvGyqc0ZlPi0u56bnUKJPKUo_RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});